services:
  app:
    build: ./src
    ports:
      - "8080:8080"
    network_mode: "host"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "mldb"
      POSTGRES_USER: "ml_user"
      POSTGRES_PASSWORD: "pgpass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - mldb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    #network_mode: "host"

volumes:
  mldb-data:
