name: build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: run app
        run: |
          cd ./src
          sudo docker build -t my_build .
          docker-compose up
