name: build

on:
  push:
    branches: 
    - "main"
    - ".*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker:27.4.0
      
    steps:
      - uses: actions/checkout@v4

      - name: run app
        run: |
          cd ./src
          docker compose up
