name: build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: run app
        run: |
          cd ./src
          sudo docker build -t my_build .
          docker-compose up
